### ISSUE TITLE
Mono not found  - mono 3.10 IS installed

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/omnisharp-brackets#54]
Running omnisharp-brackets 0.3.2, ran install.sh with no issues all packages installed.

Console output

```
Library/Application Support/Brackets/extensions/user/omnisharp-brackets/node/server/approot/packages/kre-mono.1.0.0-beta3/bin/klr: line 14: exec: mono: not found
```

**Comment by davidfowl** [comment]
Was the expectation that mono would be installed when installing omnisharp?

**Comment by spboyer** [comment]
No, I'm saying that I have mono installed.

**Comment by davidfowl** [comment]
What OS?

**Comment by spboyer** [comment]
OSX - Yosemite 10.10.2

**Comment by mat-mcloughlin** [comment]
How did you install it?

**Comment by mat-mcloughlin** [comment]
Mono that is

**Comment by spboyer** [comment]
brew install mono

**Comment by mat-mcloughlin** [comment]
Yeah, thats why. It doesn't link it to the correct path @nosami what was the fix you gave me?

It works if you install it from the website

**Comment by spboyer** [comment]
@mat-mcloughlin thats what I was just looking at.  It would be a standard for _most_ users.

**Comment by mat-mcloughlin** [comment]
yeah I know. Something I need to work around. PATH variable doesn't get past into brackets correctly (or atom) so I'm going to have this problem with the klr too
