### ISSUE TITLE
Instructions for installing are unclear

### ISSUE THREAD

**Issue by guardrex** [OmniSharp/omnisharp-brackets#55]
When you go to the Extensions Manager and find omnisharp-brackets, there is a note that states you must run an install script from an extension folder to get it to work. The problem is that people won't know how to get to that folder, and the Github repo doesn't say how to get there when you follow the 'more info' link.

Add a line either to the note for the extension itself and/or a note in the README.md that states that you need to go to Help > Show Extensions Folder, then look in user\omnisharp-brackets to find the install script.

**Comment by GuardRex** [comment]
Didn't work anyway ... running the script as an admin triggers a command window that appears for a half-second. Brackets shows the omnisharp flame icon, but it can't be started. There are no exceptions to report. Running the script with Brackets open or closed has the same result.

**Comment by GuardRex** [comment]
If the extension can't be installed this way ... if one **must** follow the manual steps indicated by the ReadMe, then the note with the extension that shows up in the Extension Manager should state this is the case ... and the ReadMe should also say 'don't use the extension manager.'

**Comment by GuardRex** [comment]
'npm is not recognized as an internal or external command' is the exception from the script ... presumably the node package manager must be installed. Good grief!
