### ISSUE TITLE
Unable to install omnisharp-brackets under Windows 10

### ISSUE THREAD

**Issue by chemscobra** [OmniSharp/omnisharp-brackets#61]
I'm trying to install omnisharp-brackets extension but it fails. I follow the instructions as is says on the brackets extension manager. 
![bra1](https://cloud.githubusercontent.com/assets/2581610/14109462/f6f311dc-f58b-11e5-84ba-d2b03251f354.png)

After I go to the extension directory and run the Install script. this message displays

![bra2](https://cloud.githubusercontent.com/assets/2581610/14109486/1b7b424a-f58c-11e5-8503-a44e1ba9e4c7.png)

Do I have to install omnisharp-roslyn binaries manually?

**Comment by willl** [comment]
Hi, I don't think anyone is looking after omnisharp-brackets these days.

Also I think that repository `omnisharp-server-roslyn-binaries` no longer exists. I don't know how the omnisharp-brackets extension works. That said, a copy of the latest binaries is available from the [omnisharp-roslyn repo/releases page](https://github.com/OmniSharp/omnisharp-roslyn/releases) but there will probably be changes that need to be made to get it to work.

If you're not set on using Brackets, you can download Atom and use the [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) plogin or just grab [VS Code](http://code.visualstudio.com/). Both of them are more actively developed and utilise omnisharp-roslyn as omnisharp-brackets does.

**Comment by chemscobra** [comment]
Hi, I see.

Yes I noticed that the repository was deleted.I managed to manually install
the plugin locally with npm, that way i could get the server to start from
brackets, but still there is no response in autocompletion.

I was using atom, but lately there where some changes in the omnisharp-atom
plugin and now is not working form me even with different atom versions
(stable and beta). Now I changed to VS and  It works amazing!. Thanks

On Tue, Mar 29, 2016 at 11:18 PM, William Luu notifications@github.com
wrote:

> Hi, I don't think anyone is looking after omnisharp-brackets these days.
> 
> Also I think that repository omnisharp-server-roslyn-binaries no longer
> exists. I don't know how the omnisharp-brackets extension works. That said,
> a copy of the latest binaries is available from the omnisharp-roslyn
> repo/releases page
> https://github.com/OmniSharp/omnisharp-roslyn/releases but there will
> probably be changes that need to be made to get it to work.
> 
> If you're not set on using Brackets, you can download Atom and use the
> omnisharp-atom https://github.com/OmniSharp/omnisharp-atom plogin or
> just grab VS Code http://code.visualstudio.com/. Both of them are more
> actively developed and utilise omnisharp-roslyn as omnisharp-brackets does.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/OmniSharp/omnisharp-brackets/issues/61#issuecomment-203233740

##

**Comment by jacrys** [comment]
in Windows,
1. Run `cd %USERPROFILE%\AppData\Roaming\Brackets\extensions\user\omnisharp-brackets`
2. Run  `npm install omnisharp-server-roslyn-binaries`
3. Open `Explorer.exe`
4. Navigate to `%USERPROFILE%\AppData\Roaming\Brackets\extensions\user\omnisharp-brackets\node_modules\omnisharp-server-roslyn-binaries\lib\server\approot\packages\kre-clr-win-x86.1.0.0-beta3\bin\lib\Microsoft.Framework.DesignTimeHost`
5. Copy `Microsoft.Framework.DesignTimeHost.dll`
6. Navigate to `%USERPROFILE%\AppData\Roaming\Brackets\extensions\user\omnisharp-brackets\node\server\approot\packages\kre-clr-win-x86.1.0.0-beta3\bin\lib\Microsoft.Framework.DesignTimeHost'
7. Paste the copied `Microsoft.Framework.DesignTimeHost.dll`
8. PROFIT!!!!

This is essentially what install.cmd did.
